server.port: 8088
spring.application.name: app1
spring.sleuth.sampler.percentage: 1.0
spring.zipkin.baseUrl: http://localhost:9411
management:
  server.port: 10080
  endpoints:
    web.exposure.include: '*'
    base-path: /management
  # 全局通用tag标识application name
  metrics.tags.application: ${spring.application.name}
